AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - '**/*~'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - '**/factories/**/*'

Documentation:
  Enabled: false
